package main

import (
	"fmt"
	"os"

	"github.com/lohtbrok/deviceos/internal/config"
	"gopkg.in/yaml.v3"
)

func cmdInit() {
	fmt.Println("Initializing DeviceOS project...")

	configPath := "deviceos.yaml"
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		cfg := config.Default()
		data, err := yaml.Marshal(cfg)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: failed to marshal config: %v\n", err)
			os.Exit(1)
		}
		header := []byte("# DeviceOS Configuration\n" +
			"# Generated by 'deviceos init'\n" +
			"# All values can also be set via environment variables (prefix: DEVICEOS_).\n\n")
		if err := os.WriteFile(configPath, append(header, data...), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error: failed to write config: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("  created %s\n", configPath)
	} else {
		fmt.Printf("  %s already exists, skipping\n", configPath)
	}

	for _, dir := range []string{"data"} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "error: failed to create %s: %v\n", dir, err)
			os.Exit(1)
		}
		fmt.Printf("  created %s/\n", dir)
	}

	fmt.Println("\nDone. Run 'deviceos start' to launch the server.")
}
