package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/lohtbrok/deviceos/internal/config"
	"gopkg.in/yaml.v3"
)

func cmdInit() {
	fmt.Println("Initializing DeviceOS project...")

	configPath := "deviceos.yaml"
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		cfg := config.Default()
		data, err := yaml.Marshal(cfg)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: failed to marshal config: %v\n", err)
			os.Exit(1)
		}
		header := []byte("# DeviceOS Configuration\n" +
			"# Generated by 'deviceos init'\n" +
			"# All values can also be set via environment variables (prefix: DEVICEOS_).\n\n")
		if err := os.WriteFile(configPath, append(header, data...), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error: failed to write config: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("  created %s\n", configPath)
	} else {
		fmt.Printf("  %s already exists, skipping\n", configPath)
	}

	for _, dir := range []string{"data/sparkdb", "data/backups"} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "error: failed to create %s: %v\n", dir, err)
			os.Exit(1)
		}
		fmt.Printf("  created %s/\n", dir)
	}

	sparkdbPath := detectSparkDB()
	if sparkdbPath == "" {
		fmt.Println("\n  SparkDB binary not found in PATH or common locations.")
		fmt.Println("  Download it from https://github.com/sparkdb/sparkdb/releases")
		fmt.Println("  Then place it in the current directory or add to PATH.")
	} else {
		abs, _ := filepath.Abs(sparkdbPath)
		fmt.Printf("  SparkDB found at %s\n", abs)
	}

	fmt.Println("\nDone. Run 'deviceos start' to launch the server.")
}

func detectSparkDB() string {
	if exe, err := os.Executable(); err == nil {
		exeDir := filepath.Dir(exe)
		p := filepath.Join(exeDir, "sparkdb")
		if fi, err := os.Stat(p); err == nil && !fi.IsDir() {
			return p
		}
	}
	for _, loc := range []string{
		"./sparkdb",
		"sparkdb",
		"./bin/sparkdb",
	} {
		if fi, err := os.Stat(loc); err == nil && !fi.IsDir() {
			abs, _ := filepath.Abs(loc)
			return abs
		}
	}
	if bin, err := exec.LookPath("sparkdb"); err == nil {
		return bin
	}
	return ""
}
